name: Build Android APK

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      
    - name: Cache Gradle packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('android/**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
          
    - name: Grant execute permission for gradlew
      run: chmod +x android/gradlew
      
    - name: Build Debug APK with Lint Bypass
      working-directory: android
      run: ./gradlew assembleDebug -Plint.abortOnError=false -x lint --stacktrace --info
      
    - name: List build outputs (debug)
      run: find android/app/build/outputs -name "*.apk" -type f
      
    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: knets-jr-debug-apk
        path: |
          android/app/build/outputs/apk/debug/*.apk
          android/app/build/outputs/apk/**/*debug*.apk
        if-no-files-found: warn
        retention-days: 7
